version: '3'

services:
  blog-mysql:
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root # root密码(修改要同时修改data/mysql/init/init.sql中的密码)
    ports:
      - "3307:3306"
    volumes:
      - /home/project/data/blog/mysql/data:/var/lib/mysql
      - /home/project/data/blog/mysql/conf:/etc/mysql/conf.d/
      - ./deploy/sql/init:/docker-entrypoint-initdb.d/
    networks:
      - blog-net

  blog:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /home/project/data/blog/logs/video/api/logs/:/app/log

    depends_on:
      - blog-mysql
    networks:
      - blog-net

networks:
  blog-net:
    driver: bridge